### ISSUE TITLE
Use specified icons in application.yml for all views

### ISSUE THREAD

**Issue by octaviospain** [roskenet/springboot-javafx-support#62]
At this moment the icons that are specified in the `application.yml` file in this way
```yaml
javafx:
  appicons:
    - /icons/icon_16x16.png
    - /icons/icon_24x24.png
    - /icons/icon_36x36.png
    - /icons/icon_42x42.png
    - /icons/icon_64x64.png
```
are only used for the first view/stage that is loaded when calling
```java
launchApp(MyJavaFxApplication.class, StartView.class, new SplashScreen(), args);
```

When other views are loaded, the specified icons are not set for the correspondent stage.

This could be done by getting the icons via `GUIState.getStage().getIcons()` when constructing the `Stage` in `AbstractFxmlView` and therefore the icons would be used for all the views.
